/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void mass_change(GSlider source, GEvent event) { //_CODE_:sliderMass:619737:
} //_CODE_:sliderMass:619737:

public void restDensity_change(GSlider source, GEvent event) { //_CODE_:sliderRestDensity:745241:
} //_CODE_:sliderRestDensity:745241:

public void fluidViscosity_change(GSlider source, GEvent event) { //_CODE_:sliderFluidViscosity:680732:

} //_CODE_:sliderFluidViscosity:680732:

public void update_click(GButton source, GEvent event) { //_CODE_:btnUpdate:391167:

  int newParticlesNum = Integer.parseInt(txtParticlesNum.getText());
  float newTimeStep = Float.parseFloat(txtTimeStep.getText());
  if ((newTimeStep!=0) && (newParticlesNum!=0))
  {
    float newMass = sliderMass.getValueF();
    float newRestDensity = sliderRestDensity.getValueF();
    float newH = sliderH.getValueF();
    float newFluidViscosity = sliderFluidViscosity.getValueF();
    currentFluid.setTimeStep(newTimeStep);
    currentFluid.setRestDensity(newRestDensity);
    currentFluid.setH(newH);
    currentFluid.setFluidViscosity(newFluidViscosity);
    currentFluid.setParticlesNumber(newParticlesNum); 
    currentFluid.updateParticles(newParticlesNum, newMass, newRestDensity);
  }
} //_CODE_:btnUpdate:391167:

public void txtParticlesNum_change(GTextField source, GEvent event) { //_CODE_:txtParticlesNum:283906:
} //_CODE_:txtParticlesNum:283906:

public void txtTimeStep_change(GTextField source, GEvent event) { //_CODE_:txtTimeStep:694139:
} //_CODE_:txtTimeStep:694139:

public void sliderH_change(GSlider source, GEvent event) { //_CODE_:sliderH:211409:
} //_CODE_:sliderH:211409:

public void play(GButton source, GEvent event) { //_CODE_:btnPlay:832565:
  loop();
} //_CODE_:btnPlay:832565:

public void pause(GButton source, GEvent event) { //_CODE_:btnPause:309183:
  noLoop();
} //_CODE_:btnPause:309183:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Controller Window");
  lblHeader = new GLabel(this, 41, 46, 396, 42);
  lblHeader.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblHeader.setText("SPH Fluid Simulation");
  lblHeader.setOpaque(false);
  lblMass = new GLabel(this, 363, 216, 80, 20);
  lblMass.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblMass.setText("Mass(gr.)");
  lblMass.setOpaque(false);
  lblRestDensity = new GLabel(this, 337, 451, 141, 34);
  lblRestDensity.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblRestDensity.setText("Rest Density");
  lblRestDensity.setOpaque(false);
  lblFluidViscosity = new GLabel(this, 57, 356, 80, 20);
  lblFluidViscosity.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblFluidViscosity.setText("µ");
  lblFluidViscosity.setOpaque(false);
  sliderMass = new GSlider(this, 350, 246, 100, 53, 10.0);
  sliderMass.setShowValue(true);
  sliderMass.setShowLimits(true);
  sliderMass.setLimits(0.5, 0.2, 1.0);
  sliderMass.setShowTicks(true);
  sliderMass.setNumberFormat(G4P.DECIMAL, 2);
  sliderMass.setLocalColorScheme(GCScheme.RED_SCHEME);
  sliderMass.setOpaque(false);
  sliderMass.addEventHandler(this, "mass_change");
  sliderRestDensity = new GSlider(this, 357, 505, 100, 53, 10.0);
  sliderRestDensity.setShowValue(true);
  sliderRestDensity.setShowLimits(true);
  sliderRestDensity.setLimits(0.5, 0.1, 1.0);
  sliderRestDensity.setShowTicks(true);
  sliderRestDensity.setNumberFormat(G4P.DECIMAL, 2);
  sliderRestDensity.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  sliderRestDensity.setOpaque(false);
  sliderRestDensity.addEventHandler(this, "restDensity_change");
  sliderFluidViscosity = new GSlider(this, 47, 391, 100, 51, 10.0);
  sliderFluidViscosity.setShowValue(true);
  sliderFluidViscosity.setShowLimits(true);
  sliderFluidViscosity.setLimits(0.5, 0.1, 1.5);
  sliderFluidViscosity.setShowTicks(true);
  sliderFluidViscosity.setNumberFormat(G4P.DECIMAL, 2);
  sliderFluidViscosity.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  sliderFluidViscosity.setOpaque(false);
  sliderFluidViscosity.addEventHandler(this, "fluidViscosity_change");
  lblParticleOptions = new GLabel(this, 301, 111, 194, 75);
  lblParticleOptions.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblParticleOptions.setText("Particle Options");
  lblParticleOptions.setOpaque(false);
  lblFluidOptions = new GLabel(this, 9, 119, 206, 69);
  lblFluidOptions.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblFluidOptions.setText("Fluid Options");
  lblFluidOptions.setOpaque(false);
  btnUpdate = new GButton(this, 192, 837, 80, 35);
  btnUpdate.setText("Update");
  btnUpdate.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  btnUpdate.addEventHandler(this, "update_click");
  txtParticlesNum = new GTextField(this, 48, 219, 120, 30, G4P.SCROLLBARS_NONE);
  txtParticlesNum.setPromptText("Number of Particles");
  txtParticlesNum.setOpaque(false);
  txtParticlesNum.addEventHandler(this, "txtParticlesNum_change");
  txtTimeStep = new GTextField(this, 46, 270, 120, 30, G4P.SCROLLBARS_NONE);
  txtTimeStep.setPromptText("Time Step");
  txtTimeStep.setOpaque(true);
  txtTimeStep.addEventHandler(this, "txtTimeStep_change");
  lblH = new GLabel(this, 355, 321, 80, 20);
  lblH.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblH.setText("h");
  lblH.setOpaque(false);
  sliderH = new GSlider(this, 353, 353, 100, 57, 10.0);
  sliderH.setShowValue(true);
  sliderH.setShowLimits(true);
  sliderH.setLimits(0.5, 0.1, 1.0);
  sliderH.setShowTicks(true);
  sliderH.setNumberFormat(G4P.DECIMAL, 2);
  sliderH.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  sliderH.setOpaque(false);
  sliderH.addEventHandler(this, "sliderH_change");
  lblParticlesNum = new GLabel(this, 756, 787, 274, 33);
  lblParticlesNum.setText("Number Of Particles:");
  lblParticlesNum.setOpaque(false);
  lblSimulation = new GLabel(this, 836, 12, 166, 64);
  lblSimulation.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblSimulation.setText("Simulation");
  lblSimulation.setOpaque(false);
  lblCurrent = new GLabel(this, 851, 746, 198, 36);
  lblCurrent.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblCurrent.setText("Current Details:");
  lblCurrent.setOpaque(false);
  lblCurrMass = new GLabel(this, 1032, 788, 133, 29);
  lblCurrMass.setText("Mass:");
  lblCurrMass.setOpaque(false);
  lblcurrH = new GLabel(this, 1035, 819, 131, 33);
  lblcurrH.setText("h:");
  lblcurrH.setOpaque(false);
  lblCurrRestDensity = new GLabel(this, 1035, 855, 133, 33);
  lblCurrRestDensity.setText("Rest Density:");
  lblCurrRestDensity.setOpaque(false);
  lblCurrMyu = new GLabel(this, 757, 823, 275, 28);
  lblCurrMyu.setText("µ:");
  lblCurrMyu.setOpaque(false);
  lblCurrTimeStep = new GLabel(this, 757, 853, 276, 35);
  lblCurrTimeStep.setText("Time Step:");
  lblCurrTimeStep.setOpaque(false);
  btnPlay = new GButton(this, 1304, 205, 80, 30);
  btnPlay.setText("Play");
  btnPlay.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  btnPlay.addEventHandler(this, "play");
  btnPause = new GButton(this, 1304, 244, 80, 30);
  btnPause.setText("Pause");
  btnPause.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  btnPause.addEventHandler(this, "pause");
}

// Variable declarations 
// autogenerated do not edit
GLabel lblHeader; 
GLabel lblMass; 
GLabel lblRestDensity; 
GLabel lblFluidViscosity; 
GSlider sliderMass; 
GSlider sliderRestDensity; 
GSlider sliderFluidViscosity; 
GLabel lblParticleOptions; 
GLabel lblFluidOptions; 
GButton btnUpdate; 
GTextField txtParticlesNum; 
GTextField txtTimeStep; 
GLabel lblH; 
GSlider sliderH; 
GLabel lblParticlesNum; 
GLabel lblSimulation; 
GLabel lblCurrent; 
GLabel lblCurrMass; 
GLabel lblcurrH; 
GLabel lblCurrRestDensity; 
GLabel lblCurrMyu; 
GLabel lblCurrTimeStep; 
GButton btnPlay; 
GButton btnPause; 
